[[main]]
name = "About"
url = "/#about"
weight = 2

[[main]]
name = "Research"
url = "/research/"
weight = 3

[[main]]
name = "Team"
url = "/#team"
weight = 4

[[main]]
name = "Teaching"
url = "/#teaching"
weight = 5


[[main]]
name = "Service"
url = "/#service"
weight = 6


[[main]]
name = "Skills"
url = "/#skills"
weight = 6

# [[main]]
# name = "Experience"
# url = "/#experience"
# weight = 6

# [[main]]
# name = "Contact"
# url = "/#contact"
# weight = 7

# [[main]]
# name = "Tech Stack"
# url = "/#technical"
# weight = 8

[[main]]
name = "Blog"
url = "/blog/"
weight = 60

[[main]]
name = "Engineering"
url = "/engineering/"
weight = 50
pre = "engineering"

[[main]]
name = "Contributions"
url = "/contributions/"
weight = 51
pre = "contributions"

